### ISSUE TITLE
1.16.4 mining gadget quartz block=infinfite gold

### ISSUE THREAD

**Issue by kamyflouge** [Jonathing/ForageCraft#73]
I'm not sure if it's on your side or Direwolf20's but if you hit the nether quartz ore with mining gadget it drops a golden nugget as soon as it changes into the render block and then you can stop mining it and it turns back into the ore . so you can just keep doing that for nugget duping

**Comment by Jonathing** [comment]
This seems like something I can't fix quite yet because I have no idea how Direwolf's mining gadget works. The way the foraging system works is that the potential drops are run through a method that determines if a forage drop is executed on every block broken. I'll probably find a better way to call this system by limiting foraging per chunk, but for now, I'll keep this issue up as it'll be important for me to figure out in the very near future.
